<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="logintest1(failed)">
    <classes>
      <class name="com.zoho.suitea.LoginTest1">
        <methods>
          <include name="loginTest" invocation-numbers="0 1 2"/>
          <include name="quit"/>
          <include name="init"/>
        </methods>
      </class> <!-- com.zoho.suitea.LoginTest1 -->
    </classes>
  </test> <!-- logintest1(failed) -->
  <test thread-count="5" name="loginTest2(failed)">
    <classes>
      <class name="com.zoho.suitea.LoginTest2">
        <methods>
          <include name="quit"/>
          <include name="loginTest" invocation-numbers="0 1 2"/>
          <include name="init"/>
        </methods>
      </class> <!-- com.zoho.suitea.LoginTest2 -->
    </classes>
  </test> <!-- loginTest2(failed) -->
</suite> <!-- Failed suite [Suite] -->
