<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="0" failed="3" skipped="6">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-15T19:29:35 IST" name="Suite" finished-at="2023-03-15T19:30:28 IST" duration-ms="52912">
    <groups>
    </groups>
    <test started-at="2023-03-15T19:29:35 IST" name="logintest1" finished-at="2023-03-15T19:30:18 IST" duration-ms="43502">
      <class name="com.zoho.suitea.LoginTest1">
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:29:36 IST" name="init" finished-at="2023-03-15T19:29:38 IST" duration-ms="2068" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest1.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:29:38 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:17 IST" duration-ms="38667" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=Y, RunMode=Y, Password=Ishu@284128, UserName=bloggerdelhi123@gmail.com, UserNameValid=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:49153/devtools/browser/40646770-5a87-4f5f-8284-2b838a7f8df8
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-HMKMG6M', ip: '192.168.29.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ZohoDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:49153/devtools/browser/40646770-5a87-4f5f-8284-2b838a7f8df8
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-HMKMG6M', ip: '192.168.29.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ZohoDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:89)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:117)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:55)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:61)
at org.openqa.selenium.chromium.ChromiumDevToolsLocator.getChromeConnector(ChromiumDevToolsLocator.java:80)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:82)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:150)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
at com.zoho.web.ZohoDriver.OpenBrowser(ZohoDriver.java:54)
at com.zoho.pages.normal.LaunchPage.OpenBrowser(LaunchPage.java:14)
at com.zoho.suitea.LoginTest1.loginTest(LoginTest1.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:17 IST" name="quit" finished-at="2023-03-15T19:30:18 IST" duration-ms="1211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:18 IST" name="init" finished-at="2023-03-15T19:30:18 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest1.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:18 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:18 IST" duration-ms="11" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=, RunMode=N, Password=, UserName=xxxxxxx, UserNameValid=N, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test case in TestNG as RunMode is mentioned as - NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test case in TestNG as RunMode is mentioned as - NO
at com.zoho.suitea.LoginTest1.loginTest(LoginTest1.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:18 IST" name="quit" finished-at="2023-03-15T19:30:18 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:18 IST" name="init" finished-at="2023-03-15T19:30:18 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest1.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:18 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:18 IST" duration-ms="6" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=N, RunMode=N, Password=xxxxx, UserName=bloggerdelhi123@gmail.com, UserNameValid=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test case in TestNG as RunMode is mentioned as - NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test case in TestNG as RunMode is mentioned as - NO
at com.zoho.suitea.LoginTest1.loginTest(LoginTest1.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suitea.LoginTest1@35f26e72]" started-at="2023-03-15T19:30:18 IST" name="quit" finished-at="2023-03-15T19:30:18 IST" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.zoho.suitea.LoginTest1 -->
    </test> <!-- logintest1 -->
    <test started-at="2023-03-15T19:30:19 IST" name="loginTest2" finished-at="2023-03-15T19:30:28 IST" duration-ms="9257">
      <class name="com.zoho.suitea.LoginTest2">
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:19 IST" name="init" finished-at="2023-03-15T19:30:19 IST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest2.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:19 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:28 IST" duration-ms="8938" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=Y, RunMode=Y, Password=Ishu@284128, UserName=bloggerdelhi123@gmail.com, UserNameValid=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:49171/devtools/browser/8e117205-e3f9-48a6-96ba-7acb3ef97118
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-HMKMG6M', ip: '192.168.29.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ZohoDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:49171/devtools/browser/8e117205-e3f9-48a6-96ba-7acb3ef97118
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-HMKMG6M', ip: '192.168.29.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ZohoDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:89)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:117)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:55)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:61)
at org.openqa.selenium.chromium.ChromiumDevToolsLocator.getChromeConnector(ChromiumDevToolsLocator.java:80)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:82)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:150)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
at com.zoho.web.ZohoDriver.OpenBrowser(ZohoDriver.java:54)
at com.zoho.pages.normal.LaunchPage.OpenBrowser(LaunchPage.java:14)
at com.zoho.suitea.LoginTest2.loginTest(LoginTest2.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="quit" finished-at="2023-03-15T19:30:28 IST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="init" finished-at="2023-03-15T19:30:28 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest2.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:28 IST" duration-ms="11" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=, RunMode=N, Password=, UserName=xxxxxxx, UserNameValid=N, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test case in TestNG as RunMode is mentioned as - NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test case in TestNG as RunMode is mentioned as - NO
at com.zoho.suitea.LoginTest2.loginTest(LoginTest2.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="quit" finished-at="2023-03-15T19:30:28 IST" duration-ms="78" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="init" finished-at="2023-03-15T19:30:28 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest2.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:28 IST" duration-ms="13" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=N, RunMode=N, Password=xxxxx, UserName=bloggerdelhi123@gmail.com, UserNameValid=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test case in TestNG as RunMode is mentioned as - NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test case in TestNG as RunMode is mentioned as - NO
at com.zoho.suitea.LoginTest2.loginTest(LoginTest2.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suitea.LoginTest2@5aac4250]" started-at="2023-03-15T19:30:28 IST" name="quit" finished-at="2023-03-15T19:30:28 IST" duration-ms="35" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.zoho.suitea.LoginTest2 -->
    </test> <!-- loginTest2 -->
  </suite> <!-- Suite -->
  <suite started-at="2023-03-15T19:30:28 IST" name="Suite (0)" finished-at="2023-03-15T19:30:50 IST" duration-ms="21733">
    <groups>
    </groups>
    <test started-at="2023-03-15T19:30:28 IST" name="loginTest3" finished-at="2023-03-15T19:30:50 IST" duration-ms="21733">
      <class name="com.zoho.suiteb.LoginTest3">
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:28 IST" name="init" finished-at="2023-03-15T19:30:28 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest3.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:28 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:50 IST" duration-ms="21555" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=Y, RunMode=Y, Password=Ishu@284128, UserName=bloggerdelhi123@gmail.com, UserNameValid=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.remote.http.ConnectionFailedException">
            <message>
              <![CDATA[Unable to establish websocket connection to http://localhost:49189/devtools/browser/4b5e982d-a41f-4f49-b8e9-7d5b990cc304
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-HMKMG6M', ip: '192.168.29.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ZohoDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:49189/devtools/browser/4b5e982d-a41f-4f49-b8e9-7d5b990cc304
Build info: version: '4.0.0-alpha-5', revision: 'b3a0d621cc'
System info: host: 'DESKTOP-HMKMG6M', ip: '192.168.29.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: ZohoDriver
at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:89)
at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:117)
at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:55)
at org.openqa.selenium.devtools.Connection.<init>(Connection.java:61)
at org.openqa.selenium.chromium.ChromiumDevToolsLocator.getChromeConnector(ChromiumDevToolsLocator.java:80)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:82)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:150)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
at com.zoho.web.ZohoDriver.OpenBrowser(ZohoDriver.java:54)
at com.zoho.pages.normal.LaunchPage.OpenBrowser(LaunchPage.java:14)
at com.zoho.suiteb.LoginTest3.loginTest(LoginTest3.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.http.ConnectionFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="quit" finished-at="2023-03-15T19:30:50 IST" duration-ms="65" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="init" finished-at="2023-03-15T19:30:50 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest3.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:50 IST" duration-ms="13" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=, RunMode=N, Password=, UserName=xxxxxxx, UserNameValid=N, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test case in TestNG as RunMode is mentioned as - NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test case in TestNG as RunMode is mentioned as - NO
at com.zoho.suiteb.LoginTest3.loginTest(LoginTest3.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="quit" finished-at="2023-03-15T19:30:50 IST" duration-ms="27" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="init(org.testng.ITestResult)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="init" finished-at="2023-03-15T19:30:50 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest3.loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="loginTest" data-provider="getData" finished-at="2023-03-15T19:30:50 IST" duration-ms="6" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PasswordNameValid=N, RunMode=N, Password=xxxxx, UserName=bloggerdelhi123@gmail.com, UserNameValid=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test case in TestNG as RunMode is mentioned as - NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test case in TestNG as RunMode is mentioned as - NO
at com.zoho.suiteb.LoginTest3.loginTest(LoginTest3.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.zoho.suiteb.LoginTest3@6492fab5]" started-at="2023-03-15T19:30:50 IST" name="quit" finished-at="2023-03-15T19:30:50 IST" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.zoho.suiteb.LoginTest3 -->
    </test> <!-- loginTest3 -->
  </suite> <!-- Suite (0) -->
  <suite started-at="2023-03-15T19:30:50 IST" name="SuiteCombined" finished-at="2023-03-15T19:30:50 IST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- SuiteCombined -->
</testng-results>
